import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <nav>
          <ul className="flex flex-row justify-around">
            <Link href="/">Home</Link>
            <Link href="/page1">page1</Link>
            <Link href="/page2">page2</Link>
          </ul>
        </nav>

        <main className="flex flex-col items-center justify-center min-h-screen py-2 ">
          {children}
        </main>
      </body>
    </html>
  );
}
