import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import { Providers } from "../components/providers";
import { ConnectButton } from "@/components/wagmi/connect-btn/connect-btn";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Providers>
          <div className="container mx-auto">
            <nav className="flex gap-2 justify-between">
              <ul className="flex flex-row gap-5">
                <Link href="/">Home</Link>
                <Link href="/infinite-scroll-examples">infinite-scroll-examples</Link>
                <Link href="/different-examples">different-examples</Link>
              </ul>
              <ConnectButton />
            </nav>
          </div>

          <main className="flex flex-col container mx-auto px-4 ">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
